/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as ListRouteImport } from './routes/list'
import { Route as FormRouteImport } from './routes/form'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/form': typeof FormRoute
  '/list': typeof ListRoute
  '/posts': typeof PostsRouteWithChildren
  '/registration': typeof RegistrationRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesByTo {
  '/form': typeof FormRoute
  '/list': typeof ListRoute
  '/posts': typeof PostsRouteWithChildren
  '/registration': typeof RegistrationRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/form': typeof FormRoute
  '/list': typeof ListRoute
  '/posts': typeof PostsRouteWithChildren
  '/registration': typeof RegistrationRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/form' | '/list' | '/posts' | '/registration' | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/form' | '/list' | '/posts' | '/registration' | '/posts/$postId'
  id:
    | '__root__'
    | '/form'
    | '/list'
    | '/posts'
    | '/registration'
    | '/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FormRoute: typeof FormRoute
  ListRoute: typeof ListRoute
  PostsRoute: typeof PostsRouteWithChildren
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
  }
}

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FormRoute: FormRoute,
  ListRoute: ListRoute,
  PostsRoute: PostsRouteWithChildren,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
