/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as OrderListRouteImport } from './routes/orderList'
import { Route as ListRouteImport } from './routes/list'
import { Route as FormRouteImport } from './routes/form'
import { Route as OrderListIndexRouteImport } from './routes/orderList.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as OrderListIdRouteImport } from './routes/orderList.$id'
import { Route as ListPageRouteImport } from './routes/list.$page'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderListRoute = OrderListRouteImport.update({
  id: '/orderList',
  path: '/orderList',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderListIndexRoute = OrderListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrderListRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const OrderListIdRoute = OrderListIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrderListRoute,
} as any)
const ListPageRoute = ListPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ListRoute,
} as any)

export interface FileRoutesByFullPath {
  '/form': typeof FormRoute
  '/list': typeof ListRouteWithChildren
  '/orderList': typeof OrderListRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/registration': typeof RegistrationRoute
  '/list/$page': typeof ListPageRoute
  '/orderList/$id': typeof OrderListIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/orderList/': typeof OrderListIndexRoute
}
export interface FileRoutesByTo {
  '/form': typeof FormRoute
  '/list': typeof ListRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/registration': typeof RegistrationRoute
  '/list/$page': typeof ListPageRoute
  '/orderList/$id': typeof OrderListIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/orderList': typeof OrderListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/form': typeof FormRoute
  '/list': typeof ListRouteWithChildren
  '/orderList': typeof OrderListRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/registration': typeof RegistrationRoute
  '/list/$page': typeof ListPageRoute
  '/orderList/$id': typeof OrderListIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/orderList/': typeof OrderListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/form'
    | '/list'
    | '/orderList'
    | '/posts'
    | '/registration'
    | '/list/$page'
    | '/orderList/$id'
    | '/posts/$postId'
    | '/orderList/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/form'
    | '/list'
    | '/posts'
    | '/registration'
    | '/list/$page'
    | '/orderList/$id'
    | '/posts/$postId'
    | '/orderList'
  id:
    | '__root__'
    | '/form'
    | '/list'
    | '/orderList'
    | '/posts'
    | '/registration'
    | '/list/$page'
    | '/orderList/$id'
    | '/posts/$postId'
    | '/orderList/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FormRoute: typeof FormRoute
  ListRoute: typeof ListRouteWithChildren
  OrderListRoute: typeof OrderListRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orderList': {
      id: '/orderList'
      path: '/orderList'
      fullPath: '/orderList'
      preLoaderRoute: typeof OrderListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orderList/': {
      id: '/orderList/'
      path: '/'
      fullPath: '/orderList/'
      preLoaderRoute: typeof OrderListIndexRouteImport
      parentRoute: typeof OrderListRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/orderList/$id': {
      id: '/orderList/$id'
      path: '/$id'
      fullPath: '/orderList/$id'
      preLoaderRoute: typeof OrderListIdRouteImport
      parentRoute: typeof OrderListRoute
    }
    '/list/$page': {
      id: '/list/$page'
      path: '/$page'
      fullPath: '/list/$page'
      preLoaderRoute: typeof ListPageRouteImport
      parentRoute: typeof ListRoute
    }
  }
}

interface ListRouteChildren {
  ListPageRoute: typeof ListPageRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListPageRoute: ListPageRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

interface OrderListRouteChildren {
  OrderListIdRoute: typeof OrderListIdRoute
  OrderListIndexRoute: typeof OrderListIndexRoute
}

const OrderListRouteChildren: OrderListRouteChildren = {
  OrderListIdRoute: OrderListIdRoute,
  OrderListIndexRoute: OrderListIndexRoute,
}

const OrderListRouteWithChildren = OrderListRoute._addFileChildren(
  OrderListRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FormRoute: FormRoute,
  ListRoute: ListRouteWithChildren,
  OrderListRoute: OrderListRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
